import = [
    "~/.config/alacritty/themes/themes/catppuccin_mocha.toml"
]

[window]

opacity = 0.3
blur = true
padding.x = 4
padding.y = 4


decorations = "Full"

[font]

normal.family = "CaskaydiaCove Nerd Font"
offset.y = 2
glyph_offset.y = 1

size = 13.0
