import = [
    "~/.config/alacritty/themes/themes/catppuccin_mocha.toml"
]

[window]

opacity = 0.9
blur = true
padding.x = 4
padding.y = 4


decorations = "Buttonless"

[font]

normal.family = "CaskaydiaCove Nerd Font"

size = 10
