"$schema" = 'https://starship.rs/config-schema.json'


add_newline = false

[git_branch]
disabled = false
[git_status]
disabled = true

[aws]
disabled = true

[package]
disabled = false

[nodejs]
disabled = false
[bun]
disabled = false

[python]
disabled = false

[conda]
disabled = false
